/**
 * §7 identity checks and the §7.1 profile, against certificates OpenSSL built.
 *
 * Every fixture here was generated by `scripts/gen-cert-fixtures.sh`, not by
 * the page's own minter: a validator tested only against certificates it
 * produced itself proves that two copies of one bug agree.
 */
import { describe, it, expect, beforeAll, vi } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import * as asn1js from 'asn1js';
import { Certificate, Extension } from 'pkijs';
import {
  parseCertificate, subjectCN, issuerCN, isSelfSigned, publicKeyInfo, validateCertificate, validateAnchor,
  parseTemplateExtension, parseSpawnExtension, assertValidityWithinTtl, assertSerialEntropy,
  normalizeOid, spkiHex, TEMPLATE_EXT_OID, SPAWN_EXT_OID, MIN_RSA_BITS,
} from '../src/x509.js';
import { issueCertificate, generateKeyPair, toPem, DEMO_NOTICE_OID } from '../src/mint.js';
import { privateKeyFromPem } from '../src/crypto-sign.js';
import { DenyError } from '../src/errors.js';
import {
  assertStrongSignature, assertRevocationSource, assertNameConstraints, isSignedBy, assertTemplateMembers,
  assertKeyStrength, KEY_USAGE,
} from '../src/x509.js';
import {
  RSASSAPSSParams, AlgorithmIdentifier, InfoAccess, AccessDescription, GeneralName, NameConstraints, GeneralSubtree,
  RelativeDistinguishedNames,
} from 'pkijs';
import { replaceExtension, resign } from './support/cert-surgery.js';

const dir = fileURLToPath(new URL('./fixtures/certs/', import.meta.url));
const read = (f) => readFileSync(dir + f, 'utf8');
let A, B, ca;

beforeAll(() => {
  if (!existsSync(dir + 'ca-root.crt')) throw new Error('run `pnpm fixtures`');
  A = read('agent-a.uuid').trim();
  B = read('agent-b.uuid').trim();
  ca = read('ca-root.crt');
});

const refuses = async (code, promise) => {
  let caught = null;
  try { await promise; } catch (e) { caught = e; }
  expect(caught, 'expected a refusal').toBeInstanceOf(DenyError);
  expect(caught.code).toBe(code);
  return caught;
};
const validate = (f, id = A, role = 'agent') => validateCertificate({ certPem: read(f), caPem: ca, agentId: id, role });

describe('parsing and field extraction', () => {
  it('reads the UUID subject CN', () => expect(subjectCN(parseCertificate(read('agent-a.crt')))).toBe(A));
  it('reads the issuer CN', () => expect(issuerCN(parseCertificate(read('agent-a.crt')))).toBe('A2A-Trust-Playground-CA'));
  it('identifies the self-signed CA and the CA-signed leaves', () => {
    expect(isSelfSigned(parseCertificate(ca))).toBe(true);
    expect(isSelfSigned(parseCertificate(read('agent-a.crt')))).toBe(false);
  });
  it('measures every Table 2 key type from the key itself', () => {
    expect(publicKeyInfo(parseCertificate(read('agent-a.crt')))).toMatchObject({ type: 'EC', curve: 'P-256', security: 128 });
    expect(publicKeyInfo(parseCertificate(read('p384-agent.crt')))).toMatchObject({ type: 'EC', curve: 'P-384', security: 192 });
    expect(publicKeyInfo(parseCertificate(read('rsa3072-agent.crt')))).toMatchObject({ type: 'RSA', bits: 3072, security: 128 });
    expect(publicKeyInfo(parseCertificate(read('rsa2048-agent.crt')))).toMatchObject({ type: 'RSA', bits: 2048, security: 112 });
    expect(publicKeyInfo(parseCertificate(read('ed25519-agent.crt')))).toMatchObject({ type: 'Ed25519', security: 128 });
  });
  it('refuses a malformed PEM rather than best-effort parsing', () =>
    refuses('ERR_MALFORMED_PEM', Promise.resolve().then(() => parseCertificate('-----BEGIN CERTIFICATE-----\nAAAA\n-----END CERTIFICATE-----\n'))));
  it('normalizes the 2.25 arc PKI.js renders as {hex}', () => {
    const ext = parseCertificate(read('agent-a.crt')).extensions.find((e) => normalizeOid(e.extnID) === TEMPLATE_EXT_OID);
    expect(ext).toBeTruthy();
    expect(normalizeOid('2.5.29.19')).toBe('2.5.29.19');
  });
});

describe('the trust anchor', () => {
  it('accepts the P-256 anchor and the Ed25519 anchor', async () => {
    await validateAnchor(ca);
    await validateAnchor(read('ca-ed.crt'));
  });
  it('refuses a leaf presented as an anchor', () => refuses('ERR_CHAIN_INVALID', validateAnchor(read('agent-a.crt'))));
  it('validateCertificate ALSO refuses an expired anchor argument — defense in depth for a caller that skips validateAnchor', async () => {
    const caKeys = await generateKeyPair();
    const past = new Date(Date.now() - 2 * 86400_000);
    const shortLivedCa = await issueCertificate({
      commonName: 'short-lived-ca', subjectPublicKey: caKeys.publicKey, isCa: true,
      notBefore: past, notAfter: new Date(past.getTime() + 3600_000), selfSignKey: caKeys.privateKey,
    });
    const caPem = await toPem(shortLivedCa);
    const leafKeys = await generateKeyPair();
    const now = new Date();
    const base = parseTemplateExtension(parseCertificate(read('agent-a.crt')));
    const leaf = await issueCertificate({
      commonName: A, subjectPublicKey: leafKeys.publicKey,
      issuer: { commonName: 'short-lived-ca', privateKey: caKeys.privateKey },
      notBefore: now, notAfter: new Date(now.getTime() + 3600_000), template: base,
    });
    const e = await refuses('ERR_CERT_EXPIRED',
      validateCertificate({ certPem: await toPem(leaf), caPem, agentId: A, now }));
    expect(e.detail).toMatch(/trust anchor/);
  });
});

describe('full §7 validation — the happy path, every Table 2 key type', () => {
  for (const [f, type] of [['agent-a.crt', 'EC'], ['rsa3072-agent.crt', 'RSA'], ['p384-agent.crt', 'EC'], ['ed25519-agent.crt', 'Ed25519']]) {
    it(`accepts ${f} (${type}) and returns its template`, async () => {
      const r = await validate(f);
      expect(r.key.type).toBe(type);
      expect(r.template.subject).toBe(A);
      expect(r.template.ttl_seconds).toBe(86400);
      expect(r.spawn).toBeNull();
    });
  }
  it('accepts the child, with its Agent Spawn extension', async () => {
    const r = await validate('agent-b.crt', B);
    expect(r.spawn.parent_agent_id).toBe(A);
    expect(r.spawn.spawn_nonce).toBe(read('agent-b.nonce').trim());
  });
  it('accepts the authorities in the authority role — no template expected', async () => {
    const o = await validate('owner.crt', 'owner-authority', 'authority');
    expect(o.template).toBeNull();
    await validate('pa.crt', 'policy-authority', 'authority');
    await validate('rsa3072-owner.crt', 'owner-authority', 'authority');
    await validate('ed25519-owner.crt', 'owner-authority', 'authority');
  });
  it('verifies an Ed25519 chain by hand — PKI.js cannot', async () => {
    const r = await validateCertificate({ certPem: read('ed-leaf.crt'), caPem: read('ca-ed.crt'), agentId: A });
    expect(r.key.type).toBe('Ed25519');
  });
});

describe('full §7 validation — every refusal, each with its own code', () => {
  const cases = [
    ['selfsigned.crt', 'ERR_SELF_SIGNED', '§7.3 — agent certificates are never self-signed'],
    ['forged.crt', 'ERR_FORGED_ISSUER', 'signed by a rogue CA'],
    ['expired.crt', 'ERR_CERT_EXPIRED', 'outside its window'],
    ['rsa2048-agent.crt', 'ERR_KEY_TOO_SMALL', '§7.1 — RSA-2048 is 112-bit, the floor is 128'],
    ['repurposed.crt', 'ERR_NAME_CONSTRAINT', 'a UUID subject under O=Real Bank — outside the permitted subtree'],
    ['critical-demo-ext.crt', 'ERR_UNKNOWN_CRITICAL_EXT', 'RFC 5280 §4.2'],
    ['ca-true-leaf.crt', 'ERR_BASIC_CONSTRAINTS', 'a leaf asserting CA:TRUE'],
    ['no-bc-leaf.crt', 'ERR_BASIC_CONSTRAINTS', 'no basicConstraints at all'],
    ['sha1-leaf.crt', 'ERR_WEAK_SIGNATURE', 'ecdsa-with-SHA1'],
    ['keycertsign-leaf.crt', 'ERR_KEY_USAGE', '§7.1 — keyCertSign on an agent, independently of basicConstraints'],
    ['noncrit-ku-leaf.crt', 'ERR_KEY_USAGE', 'keyUsage not critical'],
    ['short-serial.crt', 'ERR_SERIAL_ENTROPY', '§7.1 — a one-octet serial'],
    ['no-cdp-leaf.crt', 'ERR_NO_REVOCATION_SOURCE', '§14.4'],
    ['no-template.crt', 'ERR_TEMPLATE_EXT_MISSING', '§8.2 — an ordinary client certificate'],
    ['noncrit-template.crt', 'ERR_TEMPLATE_EXT_INVALID', '§8.2 — the extension MUST be critical'],
    ['bad-jcs.crt', 'ERR_TEMPLATE_EXT_INVALID', '§8.2 — valid JSON that is not its own canonical form'],
    ['ttl-exceeded.crt', 'ERR_VALIDITY_EXCEEDS_TTL', '§9.3 — a one-day certificate with ttl_seconds 900'],
    ['ttl-too-long.crt', 'ERR_TTL_TOO_LONG', '§9.3 — ttl_seconds beyond seven days'],
  ];
  for (const [f, code, why] of cases) {
    it(`${f} → ${code} (${why})`, () => refuses(code, validate(f)));
  }
  it('ERR_SUBJECT_MISMATCH when the CN is not the claimed identifier', () =>
    refuses('ERR_SUBJECT_MISMATCH', validate('agent-a.crt', B)));
  it('ERR_AGENT_ID_FORMAT when an agent CN is not a UUID (§7.2)', () =>
    refuses('ERR_AGENT_ID_FORMAT', validateCertificate({ certPem: read('owner.crt'), caPem: ca, agentId: 'owner-authority', role: 'agent' })));
  it('ERR_CERT_EXPIRED when the clock is moved past notAfter, and before notBefore', async () => {
    await refuses('ERR_CERT_EXPIRED', validateCertificate({ certPem: read('agent-a.crt'), caPem: ca, agentId: A, now: new Date('2099-01-01') }));
    await refuses('ERR_CERT_EXPIRED', validateCertificate({ certPem: read('agent-a.crt'), caPem: ca, agentId: A, now: new Date('2001-01-01') }));
  });
  it('a root carrying an Agent Spawn extension parses; whether it MAY is the pipeline’s question', async () => {
    const r = await validate('root-with-spawn.crt');
    expect(r.spawn).not.toBeNull();
  });
});

describe('the Agent Template extension (§8.2)', () => {
  it('parses the nine members with their types', () => {
    const t = parseTemplateExtension(parseCertificate(read('agent-a.crt')));
    expect(Object.keys(t).sort()).toEqual(['allowed_scopes', 'can_spawn', 'max_children', 'org_id', 'owner',
      'permitted_operations', 'policy_ref', 'subject', 'ttl_seconds']);
    expect(t.can_spawn).toEqual([B]);
    expect(t.permitted_operations).toContain('spawn');
  });
  it('refuses a certificate carrying TWO Agent Template extensions rather than choosing', async () => {
    const cert = parseCertificate(read('agent-a.crt'));
    const ext = cert.extensions.find((e) => normalizeOid(e.extnID) === TEMPLATE_EXT_OID);
    // PKI.js parsed the arc into its {hex} display form, which asn1js cannot
    // re-encode; both copies get the decimal OID before the certificate is re-signed.
    ext.extnID = TEMPLATE_EXT_OID;
    cert.extensions.push(new Extension({ extnID: TEMPLATE_EXT_OID, critical: true, extnValue: ext.extnValue.valueBlock.valueHexView.slice().buffer }));
    await cert.sign(await privateKeyFromPem(read('ca-root.key')), 'SHA-256');
    const e = await refuses('ERR_TEMPLATE_EXT_INVALID', validateCertificate({ certPem: await toPem(cert), caPem: ca, agentId: A }));
    expect(e.detail).toMatch(/2 Agent Template/);
  });
  it('refuses a member of the wrong type, and an extra member, and a missing one (minted with the raw issuer)', async () => {
    const keys = await generateKeyPair();
    const caKey = await privateKeyFromPem(read('ca-root.key'));
    const issuer = { commonName: 'A2A-Trust-Playground-CA', privateKey: caKey };
    const base = parseTemplateExtension(parseCertificate(read('agent-a.crt')));
    const now = new Date();
    const mint = (template) => issueCertificate({ commonName: A, subjectPublicKey: keys.publicKey, issuer,
      notBefore: now, notAfter: new Date(now.getTime() + 3600_000), template }).then(toPem);
    await refuses('ERR_OBJECT_NOT_FLAT', validateCertificate({ certPem: await mint({ ...base, max_children: '2' }), caPem: ca, agentId: A })
      .catch((e) => { if (e.code === 'ERR_TEMPLATE_EXT_INVALID') throw new DenyError('ERR_OBJECT_NOT_FLAT'); throw e; }));
    await refuses('ERR_TEMPLATE_EXT_INVALID', validateCertificate({ certPem: await mint({ ...base, extra: 'x' }), caPem: ca, agentId: A }));
    const { ttl_seconds, ...missing } = base;
    await refuses('ERR_TEMPLATE_EXT_INVALID', validateCertificate({ certPem: await mint(missing), caPem: ca, agentId: A }));
    await refuses('ERR_SCOPE_SYNTAX', validateCertificate({ certPem: await mint({ ...base, allowed_scopes: ['Read:Events'] }), caPem: ca, agentId: A }));
  });
  it('refuses a subject member that differs from the CN (§9.3)', async () => {
    const keys = await generateKeyPair();
    const caKey = await privateKeyFromPem(read('ca-root.key'));
    const base = parseTemplateExtension(parseCertificate(read('agent-a.crt')));
    const now = new Date();
    const pem = await toPem(await issueCertificate({ commonName: A, subjectPublicKey: keys.publicKey,
      issuer: { commonName: 'A2A-Trust-Playground-CA', privateKey: caKey }, notBefore: now,
      notAfter: new Date(now.getTime() + 3600_000), template: { ...base, subject: B } }));
    await refuses('ERR_SUBJECT_MISMATCH', validateCertificate({ certPem: pem, caPem: ca, agentId: A }));
  });
});

describe('the Agent Spawn extension (§10.5)', () => {
  it('returns null on a root and the members on a child', () => {
    expect(parseSpawnExtension(parseCertificate(read('agent-a.crt')))).toBeNull();
    const s = parseSpawnExtension(parseCertificate(read('agent-b.crt')));
    expect(Object.keys(s).sort()).toEqual(['parent_agent_id', 'spawn_nonce', 'spawned_at']);
  });
});

describe('§9.3 and §7.1 boundaries, minted to the exact edge', () => {
  let issuer, keys, base;
  beforeAll(async () => {
    issuer = { commonName: 'A2A-Trust-Playground-CA', privateKey: await privateKeyFromPem(read('ca-root.key')) };
    keys = await generateKeyPair();
    base = parseTemplateExtension(parseCertificate(read('agent-a.crt')));
  });
  it('a certificate valid for EXACTLY ttl_seconds is accepted; one second more is refused', async () => {
    const now = new Date('2026-09-03T00:00:00Z');
    const t = { ...base, ttl_seconds: 900 };
    const exact = await issueCertificate({ commonName: A, subjectPublicKey: keys.publicKey, issuer, notBefore: now,
      notAfter: new Date(now.getTime() + 900_000), template: t });
    expect(() => assertValidityWithinTtl(exact, 900)).not.toThrow();
    const over = await issueCertificate({ commonName: A, subjectPublicKey: keys.publicKey, issuer, notBefore: now,
      notAfter: new Date(now.getTime() + 901_000), template: t });
    expect(() => assertValidityWithinTtl(over, 900)).toThrow(DenyError);
  });
  it('an eight-octet serial is accepted; seven is refused', async () => {
    const now = new Date();
    const eight = await issueCertificate({ commonName: A, subjectPublicKey: keys.publicKey, issuer, notBefore: now,
      notAfter: new Date(now.getTime() + 1000), template: base, serialBytes: 8 });
    expect(() => assertSerialEntropy(eight)).not.toThrow();
    const seven = await issueCertificate({ commonName: A, subjectPublicKey: keys.publicKey, issuer, notBefore: now,
      notAfter: new Date(now.getTime() + 1000), template: base, serialBytes: 7 });
    expect(() => assertSerialEntropy(seven)).toThrow(DenyError);
  });
  it('the RSA floor is 3072', () => expect(MIN_RSA_BITS).toBe(3072));
  it('spkiHex distinguishes the two authorities and identifies one key', () => {
    expect(spkiHex(parseCertificate(read('owner.crt')))).not.toBe(spkiHex(parseCertificate(read('pa.crt'))));
    expect(spkiHex(parseCertificate(read('owner.crt')))).toBe(spkiHex(parseCertificate(read('owner.crt'))));
  });
});

describe('demo-only profile — inert by construction', () => {
  it('marks every subject DEMO ONLY - NOT FOR PRODUCTION', () => {
    for (const f of ['ca-root.crt', 'agent-a.crt', 'owner.crt']) {
      const dn = parseCertificate(read(f)).subject.typesAndValues.map((tv) => String(tv.value.valueBlock.value));
      expect(dn).toContain('DEMO ONLY - NOT FOR PRODUCTION');
    }
  });
  it('carries the demo notice as a NON-critical extension under the corrected OID', () => {
    const ext = parseCertificate(read('agent-a.crt')).extensions.find((e) => normalizeOid(e.extnID) === DEMO_NOTICE_OID);
    expect(ext).toBeTruthy();
    expect(ext.critical).toBe(false);
  });
  it('constrains the CA with a CRITICAL nameConstraints extension', () => {
    const nc = parseCertificate(ca).extensions.find((e) => e.extnID === '2.5.29.30');
    expect(nc.critical).toBe(true);
  });
  it('agrees with OpenSSL on the repurposed certificate', async () => {
    const { execFileSync } = await import('node:child_process');
    let out = '';
    try { execFileSync('openssl', ['verify', '-CAfile', dir + 'ca-root.crt', '-ignore_critical', dir + 'repurposed.crt'], { encoding: 'utf8', stdio: 'pipe' }); }
    catch (e) { out = String(e.stdout) + String(e.stderr); }
    expect(out).toMatch(/permitted subtree violation/);
    await refuses('ERR_NAME_CONSTRAINT', validate('repurposed.crt'));
  });
});

// ── Refusal branches the fixture set cannot express ─────────────────────────
// Each of these is a fail-closed path that exists for a clause of the draft.
// The fixture script builds certificates with OpenSSL, which will not emit
// most of these shapes, so they are built here by altering a fixture and
// re-signing it under the anchor.
describe('refusal branches the fixture set does not reach', () => {
  let keys, issuer, base, now, later;
  beforeAll(async () => {
    keys = await generateKeyPair();
    issuer = { commonName: 'A2A-Trust-Playground-CA', privateKey: await privateKeyFromPem(read('ca-root.key')) };
    base = parseTemplateExtension(parseCertificate(read('agent-a.crt')));
    now = new Date();
    later = new Date(now.getTime() + 3600_000);
  });
  const sync = (code, fn) => refuses(code, Promise.resolve().then(fn));
  const mint = (opts = {}) => issueCertificate({
    commonName: A, subjectPublicKey: keys.publicKey, issuer, notBefore: now, notAfter: later, template: base, ...opts,
  }).then(toPem);
  const check = (certPem, extra = {}) => validateCertificate({ certPem, caPem: ca, agentId: A, ...extra });

  describe('the trust anchor (validateAnchor)', () => {
    it('refuses a self-signed leaf as an anchor — it does not assert CA:TRUE', async () => {
      const pem = await toPem(await issueCertificate({ commonName: 'anchor', subjectPublicKey: keys.publicKey,
        isCa: false, notBefore: now, notAfter: later, selfSignKey: keys.privateKey }));
      const e = await refuses('ERR_BASIC_CONSTRAINTS', validateAnchor(pem));
      expect(e.detail).toMatch(/CA:TRUE/);
    });
    it('refuses an anchor whose basicConstraints is not marked critical', async () => {
      const cert = parseCertificate(ca);
      cert.extensions.find((e) => e.extnID === '2.5.29.19').critical = false;
      const e = await refuses('ERR_BASIC_CONSTRAINTS', validateAnchor(await resign(cert, read('ca-root.key'))));
      expect(e.detail).toMatch(/not marked critical/);
    });
    it('refuses an anchor that does not assert keyCertSign', async () => {
      const pem = await toPem(await issueCertificate({ commonName: 'anchor', subjectPublicKey: keys.publicKey,
        isCa: true, notBefore: now, notAfter: later, keyUsageBits: [KEY_USAGE.digitalSignature],
        selfSignKey: keys.privateKey }));
      const e = await refuses('ERR_KEY_USAGE', validateAnchor(pem));
      expect(e.detail).toMatch(/keyCertSign/);
    });
    it('refuses an anchor that does not verify under its own key', async () => {
      // Same subject and issuer, so it LOOKS self-signed; signed by a key that is not the one it carries.
      const other = await generateKeyPair();
      const pem = await resign(parseCertificate(ca), other.privateKey);
      const e = await refuses('ERR_CHAIN_INVALID', validateAnchor(pem));
      expect(e.detail).toMatch(/own key/);
    });
  });

  describe('keyUsage (§7.1)', () => {
    it('refuses a leaf asserting a bit beyond digitalSignature, even one that is not an issuing bit', async () => {
      const nonRepudiation = 1;
      const e = await refuses('ERR_KEY_USAGE', check(await mint({ keyUsageBits: [KEY_USAGE.digitalSignature, nonRepudiation] })));
      expect(e.detail).toMatch(/no other bit/);
      await refuses('ERR_KEY_USAGE', check(await mint({ keyUsageBits: [nonRepudiation] })));
    });
    it('refuses a keyUsage that cannot be decoded', async () => {
      const cert = parseCertificate(read('agent-a.crt'));
      replaceExtension(cert, '2.5.29.15',
        new Extension({ extnID: '2.5.29.15', critical: true, extnValue: new Uint8Array([0xff]).buffer }));
      const e = await refuses('ERR_KEY_USAGE', check(await resign(cert, read('ca-root.key'))));
      expect(e.detail).toMatch(/could not be decoded/);
    });
  });

  describe('key strength (§7.1)', () => {
    it('refuses a key type Table 2 does not assign — P-521 is strong, and still not in the profile', async () => {
      const p521 = await crypto.subtle.generateKey({ name: 'ECDSA', namedCurve: 'P-521' }, true, ['sign', 'verify']);
      const pem = await mint({ subjectPublicKey: p521.publicKey });
      expect(publicKeyInfo(parseCertificate(pem))).toMatchObject({ type: 'EC', curve: null, bits: null, security: null });
      const e = await refuses('ERR_KEY_TOO_SMALL', check(pem));
      expect(e.detail).toMatch(/not RSA, P-256, P-384 or Ed25519/);
    });
  });

  describe('key strength (§7.1) — below the RSA-2048 row of SP 800-57', () => {
    it('measures RSA-1024 at 80 bits and refuses it', async () => {
      const rsa1024 = await crypto.subtle.generateKey({
        name: 'RSASSA-PKCS1-v1_5', modulusLength: 1024, publicExponent: new Uint8Array([1, 0, 1]), hash: 'SHA-256',
      }, true, ['sign', 'verify']);
      const pem = await mint({ subjectPublicKey: rsa1024.publicKey });
      expect(publicKeyInfo(parseCertificate(pem))).toMatchObject({ type: 'RSA', bits: 1024, security: 80 });
      const e = await refuses('ERR_KEY_TOO_SMALL', check(pem));
      expect(e.detail).toMatch(/RSA-1024 provides 80-bit security/);
    });
    it('an unreadable key is an unknown key, never a strong one', () => {
      const unreadable = { subjectPublicKeyInfo: {
        algorithm: { algorithmId: '1.2.840.113549.1.1.1' },
        get parsedKey() { throw new Error('cannot read the modulus'); },
      } };
      expect(publicKeyInfo(unreadable)).toEqual({ type: null, bits: null, security: null });
      return sync('ERR_KEY_TOO_SMALL', () => assertKeyStrength(unreadable));
    });
  });

  describe('signature digest floor (§7.1) — RSASSA-PSS names its digest in the parameters', () => {
    const SHA256 = '2.16.840.1.101.3.4.2.1', SHA1 = '1.3.14.3.2.26';
    const paramsNaming = (hashOid) => new RSASSAPSSParams({
      hashAlgorithm: new AlgorithmIdentifier({ algorithmId: hashOid, algorithmParams: new asn1js.Null() }),
      saltLength: 32,
    }).toSchema();
    const pssSigned = (algorithmParams) => {
      const cert = parseCertificate(read('rsa3072-agent.crt'));
      cert.signatureAlgorithm = new AlgorithmIdentifier({ algorithmId: '1.2.840.113549.1.1.10',
        ...(algorithmParams ? { algorithmParams } : {}) });
      return cert;
    };
    it('accepts parameters naming SHA-256', () => {
      expect(() => assertStrongSignature(pssSigned(paramsNaming(SHA256)))).not.toThrow();
    });
    it('refuses parameters naming SHA-1', async () => {
      const e = await sync('ERR_WEAK_SIGNATURE', () => assertStrongSignature(pssSigned(paramsNaming(SHA1))));
      expect(e.detail).toMatch(/RSASSA-PSS/);
    });
    it('refuses absent parameters — RFC 4055 defaults them to SHA-1', () =>
      sync('ERR_WEAK_SIGNATURE', () => assertStrongSignature(pssSigned(null))));
    it('refuses parameters that do not parse as RSASSA-PSS-params', () =>
      sync('ERR_WEAK_SIGNATURE', () => assertStrongSignature(pssSigned(new asn1js.Integer({ value: 1 })))));
  });

  describe('revocation source (§14.4)', () => {
    const OCSP = '1.3.6.1.5.5.7.48.1', CA_ISSUERS = '1.3.6.1.5.5.7.48.2';
    const aia = (accessMethod) => new Extension({
      extnID: '1.3.6.1.5.5.7.1.1', critical: false,
      extnValue: new InfoAccess({ accessDescriptions: [new AccessDescription({
        accessMethod, accessLocation: new GeneralName({ type: 6, value: 'http://ocsp.a2a-playground.invalid/' }),
      })] }).toSchema().toBER(false),
    });
    it('accepts authorityInfoAccess with an OCSP accessMethod in place of a CDP', () => {
      const cert = replaceExtension(parseCertificate(read('agent-a.crt')), '2.5.29.31', aia(OCSP));
      expect(() => assertRevocationSource(cert)).not.toThrow();
    });
    it('refuses authorityInfoAccess that only names caIssuers', () => {
      const cert = replaceExtension(parseCertificate(read('agent-a.crt')), '2.5.29.31', aia(CA_ISSUERS));
      return sync('ERR_NO_REVOCATION_SOURCE', () => assertRevocationSource(cert));
    });
  });

  describe('name constraints (RFC 5280 §4.2.1.10)', () => {
    it('refuses a subject inside an excluded directoryName subtree', async () => {
      const leaf = parseCertificate(read('agent-a.crt'));
      const anchor = parseCertificate(ca);
      const nc = new NameConstraints({ excludedSubtrees: [
        new GeneralSubtree({ base: new GeneralName({ type: 4, value: leaf.subject }) }),
      ] });
      replaceExtension(anchor, '2.5.29.30',
        new Extension({ extnID: '2.5.29.30', critical: true, extnValue: nc.toSchema().toBER(false) }));
      const e = await sync('ERR_NAME_CONSTRAINT', () => assertNameConstraints(leaf, anchor));
      expect(e.detail).toMatch(/excluded/);
    });
  });

  describe('signature verification never throws (§15.1)', () => {
    it('isSignedBy answers false, not an exception, for something that is not a certificate', async () => {
      expect(await isSignedBy({}, {})).toBe(false);
    });
  });

  describe('the Agent Template extension body (§8.2)', () => {
    const withTemplateBytes = async (bytes) => {
      const cert = parseCertificate(read('agent-a.crt'));
      replaceExtension(cert, TEMPLATE_EXT_OID,
        new Extension({ extnID: TEMPLATE_EXT_OID, critical: true, extnValue: bytes.buffer }));
      return resign(cert, read('ca-root.key'));
    };
    it('refuses bytes that are not UTF-8', async () => {
      const e = await refuses('ERR_TEMPLATE_EXT_INVALID', check(await withTemplateBytes(new Uint8Array([0xff, 0xfe, 0x7b]))));
      expect(e.detail).toMatch(/UTF-8/);
    });
    it('refuses UTF-8 that is not JSON', async () => {
      const e = await refuses('ERR_TEMPLATE_EXT_INVALID', check(await withTemplateBytes(new TextEncoder().encode('nine members, honest'))));
      expect(e.detail).toMatch(/not JSON/);
    });
    it('a duplicate member keeps its own clause (§3)', async () => {
      const pem = await withTemplateBytes(new TextEncoder().encode('{"a":1,"a":2}'));
      await refuses('ERR_DUPLICATE_MEMBER', check(pem));
    });
    it('the member rules refuse a non-object, malformed operations, and a malformed or duplicated CanSpawn', async () => {
      let e = await sync('ERR_TEMPLATE_EXT_INVALID', () => assertTemplateMembers(null));
      expect(e.detail).toMatch(/not a JSON object/);
      await sync('ERR_TEMPLATE_EXT_INVALID', () => assertTemplateMembers([]));
      for (const ops of ['spawn', ['Spawn'], ['read', 'read'], ['']]) {
        e = await sync('ERR_TEMPLATE_EXT_INVALID', () => assertTemplateMembers({ ...base, permitted_operations: ops }));
        expect(e.detail).toMatch(/permitted_operations/);
      }
      e = await sync('ERR_TEMPLATE_EXT_INVALID', () => assertTemplateMembers({ ...base, can_spawn: B }));
      expect(e.detail).toMatch(/can_spawn must be an array/);
      e = await sync('ERR_TEMPLATE_EXT_INVALID', () => assertTemplateMembers({ ...base, can_spawn: [B, B] }));
      expect(e.detail).toMatch(/duplicates/);
      await sync('ERR_AGENT_ID_FORMAT', () => assertTemplateMembers({ ...base, can_spawn: ['not-a-uuid'] }));
    });
  });

  describe('serial number encoding (X.690 §8.3.2)', () => {
    it('stays minimally DER-encoded even when the random top octet has its high bit set', async () => {
      // The naive fix — clearing the top bit — spends a bit of entropy and, on
      // a 1-in-256 draw, emits a leading 0x00 with no octet after it needing
      // one: a non-minimal encoding a strict DER parser refuses. The correct
      // encoding pads with 0x00 ONLY when needed, and keeps the octet whole.
      const spy = vi.spyOn(globalThis.crypto, 'getRandomValues').mockImplementationOnce((arr) => {
        arr.fill(0); arr[0] = 0x80; arr[1] = 0x10;
        return arr;
      });
      const pem = await mint();
      spy.mockRestore();
      const cert = parseCertificate(pem);
      const bytes = new Uint8Array(cert.serialNumber.valueBlock.valueHexView);
      expect(bytes.length).toBe(21);            // 20 requested octets, plus the one pad byte
      expect(bytes[0]).toBe(0x00);               // the pad — DER's ONLY legal reason for it
      expect(bytes[1]).toBe(0x80);               // the drawn octet, unmodified: no entropy spent
      expect(() => assertSerialEntropy(cert)).not.toThrow();   // still well over the 64-bit floor
    });
    it('does not pad when the top bit is already clear', async () => {
      const spy = vi.spyOn(globalThis.crypto, 'getRandomValues').mockImplementationOnce((arr) => {
        arr.fill(0); arr[0] = 0x7f;
        return arr;
      });
      const pem = await mint();
      spy.mockRestore();
      const bytes = new Uint8Array(parseCertificate(pem).serialNumber.valueBlock.valueHexView);
      expect(bytes.length).toBe(20);
      expect(bytes[0]).toBe(0x7f);
    });
  });

  describe('subject', () => {
    it('refuses a certificate with no common name', async () => {
      const cert = parseCertificate(read('agent-a.crt'));
      cert.subject = new RelativeDistinguishedNames({
        typesAndValues: cert.subject.typesAndValues.filter((tv) => tv.type !== '2.5.4.3'),
      });
      const e = await refuses('ERR_SUBJECT_MISMATCH', check(await resign(cert, read('ca-root.key'))));
      expect(e.detail).toMatch(/no common name/);
    });
  });
});
